# Урок 8. Дисперсионный анализ. Логистическая регрессия

## 1. Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов. Даны значения роста в трех группах случайно выбранных спортсменов: Футболисты: 173, 175, 180, 178, 177, 185, 183, 182. Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180. Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.

In [1]:
import numpy as np

In [2]:
y1 = np.array([173, 175, 180, 178, 177, 185, 183, 182], dtype=np.float64)
y2 = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180], dtype=np.float64)
y3 = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170], dtype=np.float64)

n1 = y1.size
n2 = y2.size
n3 = y3.size
n = n1 + n2 + n3
k = 3

print(f"Значения роста футболистов:\n{y1}\n")
print(f"Всего футболистов: {n1}\n")
print(f"Значения роста хоккеистов:\n{y2}\n")
print(f"Всего хоккеистов: {n2}\n")
print(f"Значения роста штангистов:\n{y3}\n")
print(f"Всего штангистов: {n3}\n")
print(f"Всего человек: {n}")

Значения роста футболистов:
[173. 175. 180. 178. 177. 185. 183. 182.]

Всего футболистов: 8

Значения роста хоккеистов:
[177. 179. 180. 188. 177. 172. 171. 184. 180.]

Всего хоккеистов: 9

Значения роста штангистов:
[172. 173. 169. 177. 166. 180. 178. 177. 172. 166. 170.]

Всего штангистов: 11

Всего человек: 28


In [3]:
y1_mean = np.mean(y1)
y2_mean = np.mean(y2)
y3_mean = np.mean(y3)

print(f"Среднее значение роста футболистов:\n{y1_mean}\n")
print(f"Среднее значение роста хоккеистов:\n{y2_mean}\n")
print(f"Среднее значение роста штангистов:\n{y3_mean}")

Среднее значение роста футболистов:
179.125

Среднее значение роста хоккеистов:
178.66666666666666

Среднее значение роста штангистов:
172.72727272727272


In [4]:
y_all = np.concatenate([y1, y2, y3])
y_all

array([173., 175., 180., 178., 177., 185., 183., 182., 177., 179., 180.,
       188., 177., 172., 171., 184., 180., 172., 173., 169., 177., 166.,
       180., 178., 177., 172., 166., 170.])

In [5]:
y_mean = np.mean(y_all)

print(f"Среднее значение роста по всем значениям:\n{y_mean}")

Среднее значение роста по всем значениям:
176.46428571428572


In [6]:
s2 = np.sum((y_all - y_mean)**2)

print(f"Сумма квадратов отклонений наблюдений от общего среднего:\n{s2}")

Сумма квадратов отклонений наблюдений от общего среднего:
830.9642857142854


In [7]:
s2_f = ((y1_mean - y_mean)**2) * n1 + ((y2_mean - y_mean)**2) * n2 + ((y3_mean - y_mean)**2) * n3

print(f"Сумма квадратов отклонений средних групповых значений от общего среднего:\n{s2_f}")

Сумма квадратов отклонений средних групповых значений от общего среднего:
253.9074675324678


In [8]:
s2_residual = 0
for elem in y1:
    s2_residual += (elem - y1_mean)**2
for elem in y2:
    s2_residual += (elem - y2_mean)**2
for elem in y3:
    s2_residual += (elem - y3_mean)**2

print(f"Остаточная сумма квадратов отклонений:\n{s2_residual}")

Остаточная сумма квадратов отклонений:
577.0568181818181


In [9]:
print(f"Проверка:\n{s2} = {s2_f + s2_residual}")


Проверка:
830.9642857142854 = 830.9642857142859


In [10]:
sigma2_general = s2 / (n - 1)

print(f"Общая дисперсия:\n{sigma2_general}")

Общая дисперсия:
30.776455026455015


In [11]:
sigma2_f = s2_f / (k - 1)

print(f"Факторная дисперсия:\n{sigma2_f}")

Факторная дисперсия:
126.9537337662339


In [12]:
sigma2_residual = s2_residual / (n - k)

print(f"Остаточная дисперсия:\n{sigma2_residual}")

Остаточная дисперсия:
23.082272727272724


In [13]:
F_h = sigma2_f / sigma2_residual

print(f"Расчетное значение критерия Фишера-Снедекора:\n{F_h}")

Расчетное значение критерия Фишера-Снедекора:
5.500053450812599


Табличное значение критерия для $df_{межд} = k - 1 = 3 - 1 = 2$, и $df_{внутр} = n - k = 28 - 3 = 25$, при уровне значимости $\alpha = 0,05$ равно 3,38.

Так как расчетное значение больше табличного, то различие среднего роста в трех группах статистически значимо.

In [14]:
eta2 = s2_f / s2

print(f"Эмпирическое корреляционное отношение:\n{eta2}")

Эмпирическое корреляционное отношение:
0.30555761769498


In [15]:
from scipy import stats
stats.f_oneway(y1, y2, y3)

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)

### __Ответ__:  различие среднего роста в трех группах статистически значимо для уровня значимости не менее 0.010482206918698694.