# Урок 6. Взаимосвязь величин. Параметрические и непараметрические показатели корреляции. Корреляционный анализ.

## 1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):

## zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],

## ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].

## Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy. Полученные значения должны быть равны. 

## Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas.

In [1]:
import numpy as np
import pandas as pd

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

sum_zp = 0
for zp_el in zp:
    sum_zp+= zp_el

sum_ks = 0
for ks_el in ks:
    sum_ks+= ks_el
    
zp_ks = zp*ks
sum_zp_ks = 0
for zp_ks_el in zp_ks:
    sum_zp_ks+= zp_ks_el

zp_mean = sum_zp/zp.size
ks_mean = sum_ks/ks.size
zp_ks_mean = sum_zp_ks/zp_ks.size

cov_easy = zp_ks_mean - zp_mean*ks_mean
print(f"Ковариация по формуле:\n{cov_easy}\n")

cov_np = np.cov(zp, ks, ddof=0)
print(f"Ковариация методом cov библиотеки numpy:\n{cov_np}\n")


sum_zp2 = 0
for zp_el in zp:
    sum_zp2+= (zp_el-zp_mean)**2

sum_ks2 = 0
for ks_el in ks:
    sum_ks2+= (ks_el-ks_mean)**2
    
sigma_zp_easy = (sum_zp2/zp.size)**0.5
sigma_ks_easy = (sum_ks2/ks.size)**0.5

r_easy = cov_easy/(sigma_zp_easy*sigma_ks_easy)

print(f"Коэффициент корреляции Пирсона по формуле:\n{r_easy}\n")

r_np = np.corrcoef(zp, ks)

print(f"Коэффициент корреляции Пирсона методом corrcoef библиотеки numpy:\n{r_np}\n")


Ковариация по формуле:
9157.839999999997

Ковариация методом cov библиотеки numpy:
[[ 3494.64  9157.84]
 [ 9157.84 30468.89]]

Коэффициент корреляции Пирсона по формуле:
0.8874900920739158

Коэффициент корреляции Пирсона методом corrcoef библиотеки numpy:
[[1.         0.88749009]
 [0.88749009 1.        ]]



## 2. Измерены значения IQ выборки студентов, обучающихся в местных технических вузах: 131, 125, 115, 122, 131, 115, 107, 99, 125, 111. Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [3]:
X = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
X

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [4]:
X.size

10

Так как неизвестно среднее квадратическое отклонение генеральной совокупности, то используем t-критерий. Нижняя и верхняя границы доверительного интервала:

## $$T_{1,2} = \overline{X} \pm t_{\frac{\alpha}{2}} \cdot \frac{s_0}{\sqrt{n}}$$

По условию задачи:

### $$n = 10$$
### $$p = 1-\alpha = 0,95 \Rightarrow \alpha = 0,05 $$
### 

Выборочное среднее арифметическое $\overline{X}$:

In [5]:
X.mean()

118.1

Среднее квадратичное отклонение по выборке (несмещенное) $s_0$:

In [6]:
np.std(X, ddof=1)

10.54566788359614

Согласно t-таблице, для $\alpha = 0,025$ и числа степеней свободы равному $n-1 = 9$ значение $t = 2,262$

Подставив значения в формулу имеем:

In [7]:
X.mean() - 2.262*np.std(X, ddof=1)/np.sqrt(10)

110.55660776308164

In [8]:
X.mean() + 2.262*np.std(X, ddof=1)/np.sqrt(10)

125.64339223691834

### __Ответ__: [110,5566; 125,6434]

## 3.  Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

Так как известна дисперсия генеральной совокупности, то используем Z-критерий. Нижняя и верхняя границы доверительного интервала:

## $$T_{1,2} = \overline{X} \pm Z_{\frac{\alpha}{2}} \cdot \frac{\sigma}{\sqrt{n}}$$

По условию задачи:

### $$\sigma = \sqrt{D} = \sqrt{25} = 5$$
### $$M = 174.2$$
### $$n = 27$$

### $$p = 1-\alpha = 0,95 \Rightarrow \alpha = 0,05 $$

Согласно Z-таблице:

### $$Z_{\frac{\alpha}{2}} = Z_{0,025} = -1,96$$

Подставив значения в формулу имеем:

In [9]:
174.2 - 1.96*5/np.sqrt(27)

172.31398912064722

In [10]:
174.2 + 1.96*5/np.sqrt(27)

176.08601087935276

### __Ответ__: [172,314; 176,086]